'use client'
import{useEffect,useState}from'react'
import{supabase}from'@/lib/supabase'
import{useRouter}from'next/navigation'
import AgencySidebar from'@/components/AgencySidebar'
export default function DocumentsPage(){
const router=useRouter()
const[bookings,setBookings]=useState([])
const[loading,setLoading]=useState(true)
const[search,setSearch]=useState('')
useEffect(()=>{async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session){router.push('/login');return};const{data}=await supabase.from('bookings').select('*,venues(name),artists(stage_name)').not('brief_doc_url','is',null).order('date',{ascending:false});if(data)setBookings(data.filter(b=>b.brief_doc_url));setLoading(false)};load()},[]);
const filtered=bookings.filter(b=>{if(!search)return true;const s=search.toLowerCase();return(b.venues?.name||''). toLowerCase().includes(s)||(b.artists?.stage_name||''). toLowerCase().includes(s)||(b.event_name||''). toLowerCase().includes(s)})
if(loading)return(<div className="min-h-screen bg-[#0E1117] flex items-center justify-center"><div className="text-[#C8A24A] text-4xl font-bold animate-pulse">VE</div></div>)
return(<div className="min-h-screen bg-[#0E1117] flex"><AgencySidebar/><div className="flex-1 flex flex-col"><div className="bg-[#151A22] border-b border-[#263044] px-8 h-14 flex items-center"><div className="text-white font-semibold">Documents</div></div><div className="p-8"><div className="mb-6"><input type="text" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search documents..." className="w-full max-w-md bg-[#151A22] border border-[#263044] rounded-lg px-4 py-2.5 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors"/></div>{filtered.length===0&&<div className="text-center py-16"><div className="text-[#4E5A6A] text-sm mb-2">{search?'No documents match your search':'No briefs generated yet'}</div><p className="text-[#4E5A6A] text-xs">Add a Google Doc link when creating a booking to see it here</p></div>}<div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(b=>(<div key={b.id} className="bg-[#151A22] border border-[#263044] rounded-xl p-5 hover:border-[#C8A24A]/50 transition-colors"><div className="flex items-start justify-between mb-3"><div className="w-10 h-10 rounded-lg bg-[#C8A24A]/10 border border-[#C8A24A]/20 flex items-center justify-center text-lg">📄</div><span className="text-xs bg-[#1C2330] text-[#6A7A8A] border border-[#263044] px-2 py-0.5 rounded">Brief</span></div><div className="text-white font-semibold text-sm mb-0.5">{b.venues?.name}</div>{b.event_name&&<div className="text-[#6A7A8A] text-xs mb-1">{b.event_name}</div>}<div className="text-[#4E5A6A] text-xs font-mono mb-3">{b.artists?.stage_name} · {new Date(b.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</div><a href={b.brief_doc_url} target="_blank" rel="noreferrer" className="block w-full text-center bg-[#C8A24A]/10 border border-[#C8A24A]/30 rounded-lg py-2 text-[#C8A24A] text-xs font-semibold hover:bg-[#C8A24A]/20 transition-colors">Open in Google Docs →</a></div>))}</div></div></div></div>)}