'use client'
import{useState}from'react'
import{supabase}from'@/lib/supabase'
export default function LoginPage(){
const[email,setEmail]=useState('')
const[password,setPassword]=useState('')
const[error,setError]=useState('')
const[loading,setLoading]=useState(false)
async function handleLogin(e){e.preventDefault();setLoading(true);setError('');const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return};const{data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).maybeSingle();await new Promise(resolve=>setTimeout(resolve,500));if(profile?.role==='artist'){window.location.href='/artist/dashboard'}else{window.location.href='/agency/dashboard'}}
return(<div className="min-h-screen bg-[#0E1117] flex items-center justify-center px-4"><div className="w-full max-w-md"><div className="text-center mb-10"><div className="text-5xl font-bold text-[#C8A24A] mb-3">VE</div><div className="text-white text-sm font-semibold tracking-[0.2em] uppercase mb-1">Virtuoso Entertainment</div><div className="text-[#6A7A8A] text-xs tracking-widest uppercase italic">Connecting Talent. Elevating Experiences.</div></div><div className="bg-[#151A22] border border-[#263044] rounded-2xl p-8"><h1 className="text-white text-xl font-semibold mb-1">Sign in</h1><p className="text-[#6A7A8A] text-sm mb-6">Agency and artist access</p><form onSubmit={handleLogin} className="space-y-4"><div><label className="block text-[#8A96A8] text-xs uppercase tracking-widest mb-2">Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors" placeholder="your@email.com"/></div><div><label className="block text-[#8A96A8] text-xs uppercase tracking-widest mb-2">Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required className="w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors" placeholder="••••••••••"/></div>{error&&<div className="bg-red-900/20 border border-red-800 rounded-lg px-4 py-3 text-red-400 text-sm">{error}</div>}<button type="submit" disabled={loading} className="w-full bg-[#C8A24A] hover:bg-[#D6B25E] disabled:opacity-50 text-[#0E1117] font-bold py-3 rounded-lg text-sm uppercase tracking-widest transition-colors">{loading?'Signing in...':'Sign in'}</button><p className="text-center pt-1"><a href="/reset-password" className="text-[#6A7A8A] text-xs hover:text-[#C8A24A] transition-colors">Forgot your password?</a></p></form></div><p className="text-center text-[#4E5A6A] text-xs mt-6">Virtuoso Entertainment Ltd · London</p></div></div>)}