'use client'
import{useState}from 'react'
import{supabase}from '@/lib/supabase'
export default function ResetPasswordPage(){
const[email,setEmail]=useState('')
const[submitted,setSubmitted]=useState(false)
const[error,setError]=useState('')
const[loading,setLoading]=useState(false)
async function handleReset(e){e.preventDefault();setLoading(true);setError('');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/auth/callback'});if(error){setError(error.message);setLoading(false);return}setSubmitted(true);setLoading(false)}
if(submitted)return(<div className='min-h-screen bg-background flex items-center justify-center'><div className='bg-card border border-border rounded-2xl p-8 text-center'><div className='text-success text-4xl mb-4'>✓</div><h1 className='text-foreground text-xl mb-2'>Check your inbox</h1><p className='text-muted-foreground/80 text-sm'>Sent to {email}</p><a href='/login' className='text-primary text-sm mt-4 block'>Back to sign in</a></div></div>)
return(<div className='min-h-screen bg-background flex items-center justify-center px-4'><div className='w-full max-w-md'><div className='text-center mb-10'><div className='text-5xl font-bold text-primary mb-3'>VE</div><div className='text-foreground text-sm tracking-widest uppercase'>Virtuoso Entertainment</div></div><div className='bg-card border border-border rounded-2xl p-8'><h1 className='text-foreground text-xl font-semibold mb-1'>Reset password</h1><p className='text-muted-foreground/80 text-sm mb-6'>Enter your email for a reset link.</p><form onSubmit={handleReset} className='space-y-4'><div><label className='block text-muted-foreground text-xs uppercase tracking-widest mb-2'>Email</label><input type='email' value={email} onChange={e=>setEmail(e.target.value)} required className='w-full bg-secondary border border-input-border rounded-lg px-4 py-3 text-foreground text-sm focus:outline-none focus:border-primary' placeholder='your@email.com'/></div>{error&&<div className='bg-destructive/10 border border-destructive/40 rounded-lg px-4 py-3 text-destructive text-sm'>{error}</div>}<button type='submit' disabled={loading} className='w-full bg-primary hover:bg-primary/90 disabled:opacity-50 text-primary-foreground font-bold py-3 rounded-lg text-sm uppercase tracking-widest'>{loading?'Sending...':'Send reset link'}</button></form><p className='text-center mt-6'><a href='/login' className='text-primary text-sm hover:underline'>Back to sign in</a></p></div></div></div>)}