'use client'
import{useState}from 'react'
import{supabase}from '@/lib/supabase'
export default function ResetPasswordPage(){
const[email,setEmail]=useState('')
const[submitted,setSubmitted]=useState(false)
const[error,setError]=useState('')
const[loading,setLoading]=useState(false)
async function handleReset(e){e.preventDefault();setLoading(true);setError('');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/auth/callback'});if(error){setError(error.message);setLoading(false);return}setSubmitted(true);setLoading(false)}
if(submitted)return(<div className='min-h-screen bg-[#0E1117] flex items-center justify-center'><div className='bg-[#151A22] border border-[#263044] rounded-2xl p-8 text-center'><div className='text-green-400 text-4xl mb-4'>✓</div><h1 className='text-white text-xl mb-2'>Check your inbox</h1><p className='text-[#6A7A8A] text-sm'>Sent to {email}</p><a href='/login' className='text-[#C8A24A] text-sm mt-4 block'>Back to sign in</a></div></div>)
return(<div className='min-h-screen bg-[#0E1117] flex items-center justify-center px-4'><div className='w-full max-w-md'><div className='text-center mb-10'><div className='text-5xl font-bold text-[#C8A24A] mb-3'>VE</div><div className='text-white text-sm tracking-widest uppercase'>Virtuoso Entertainment</div></div><div className='bg-[#151A22] border border-[#263044] rounded-2xl p-8'><h1 className='text-white text-xl font-semibold mb-1'>Reset password</h1><p className='text-[#6A7A8A] text-sm mb-6'>Enter your email for a reset link.</p><form onSubmit={handleReset} className='space-y-4'><div><label className='block text-[#8A96A8] text-xs uppercase tracking-widest mb-2'>Email</label><input type='email' value={email} onChange={e=>setEmail(e.target.value)} required className='w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A]' placeholder='your@email.com'/></div>{error&&<div className='bg-red-900/20 border border-red-800 rounded-lg px-4 py-3 text-red-400 text-sm'>{error}</div>}<button type='submit' disabled={loading} className='w-full bg-[#C8A24A] hover:bg-[#D6B25E] disabled:opacity-50 text-[#0E1117] font-bold py-3 rounded-lg text-sm uppercase tracking-widest'>{loading?'Sending...':'Send reset link'}</button></form><p className='text-center mt-6'><a href='/login' className='text-[#C8A24A] text-sm hover:underline'>Back to sign in</a></p></div></div></div>)}