'use client'
import{useEffect,useState}from'react'
import{supabase}from'@/lib/supabase'
import{useRouter}from'next/navigation'
import AgencySidebar from'@/components/AgencySidebar'
export default function CompletedPage(){
const router=useRouter()
const[bookings,setBookings]=useState([])
const[loading,setLoading]=useState(true)
useEffect(()=>{async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session){router.push('/login');return};const{data}=await supabase.from('bookings').select('*,venues(name),artists(stage_name)').eq('brag_status','B').order('date',{ascending:false});if(data)setBookings(data);setLoading(false)};load()},[]);
const totalRevenue=bookings.reduce((s,b)=>s+(b.fee_venue||0),0)
if(loading)return(<div className="min-h-screen bg-[#0E1117] flex items-center justify-center"><div className="text-[#C8A24A] text-4xl font-bold animate-pulse">VE</div></div>)
return(<div className="min-h-screen bg-[#0E1117] flex"><AgencySidebar/><div className="flex-1 flex flex-col"><div className="bg-[#151A22] border-b border-[#263044] px-8 h-14 flex items-center"><div className="text-white font-semibold">Completed Gigs</div></div><div className="p-8"><div className="bg-[#151A22] border border-[#263044] rounded-xl p-5 mb-6 inline-block"><div className="text-[#4E5A6A] text-xs uppercase tracking-widest mb-1">Total revenue from completed gigs</div><div className="text-[#C8A24A] text-3xl font-bold">£{totalRevenue.toLocaleString()}</div><div className="text-[#4E5A6A] text-xs mt-1">{bookings.length} gig{bookings.length!==1?'s':''} completed</div></div>{bookings.length===0&&<div className="text-center py-16 text-[#4E5A6A] text-sm">No completed gigs yet</div>}<div className="flex flex-col gap-3">{bookings.map(b=>(<div key={b.id} className="bg-[#151A22] border border-[#263044] border-l-4 border-l-blue-500 rounded-xl p-4"><div className="flex items-center justify-between gap-4"><div><div className="text-white font-semibold">{b.venues?.name}</div>{b.event_name&&<div className="text-[#6A7A8A] text-xs mt-0.5">{b.event_name}</div>}<div className="flex gap-3 text-xs text-[#6A7A8A] mt-2 flex-wrap"><span>📅 {new Date(b.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span>{b.artists?.stage_name&&<span>🎧 {b.artists.stage_name}</span>}</div></div><div className="flex flex-col items-end gap-1"><span className="text-[#C8A24A] font-bold">£{(b.fee_venue||0).toLocaleString()}</span><span className="text-xs bg-blue-900/30 text-blue-400 px-2 py-0.5 rounded-full">Complete</span></div></div><div className="mt-3 pt-3 border-t border-[#263044]"><button onClick={()=>router.push('/agency/invoices')} className="text-xs text-[#C8A24A] hover:underline">View invoice →</button></div></div>))}</div></div></div></div>)}