'use client'
import{useEffect,useState}from'react'
import{supabase}from'@/lib/supabase'
import{useRouter}from'next/navigation'
import AgencySidebar from'@/components/AgencySidebar'
import NavIcon from'@/components/NavIcon'
export default function CompletedPage(){
const router=useRouter()
const[bookings,setBookings]=useState([])
const[loading,setLoading]=useState(true)
useEffect(()=>{async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session){router.push('/login');return};const{data}=await supabase.from('bookings').select('id,event_name,starts_at,fee_venue,venues(name),artists(stage_name)').eq('brag_status','B').is('cancelled_at',null).order('starts_at',{ascending:false});if(data)setBookings(data);setLoading(false)};load()},[]);
const totalRevenue=bookings.reduce((s,b)=>s+(b.fee_venue||0),0)
if(loading)return(<div className="min-h-screen bg-background flex items-center justify-center"><div className="text-primary text-4xl font-bold animate-pulse">VC</div></div>)
return(<div className="min-h-screen bg-background flex"><AgencySidebar/><div className="flex-1 flex flex-col min-w-0 pt-14 md:pt-0"><div className="bg-card border-b border-border px-4 md:px-8 h-14 flex items-center"><div className="text-foreground font-semibold">Completed Gigs</div></div><div className="p-4 md:p-8"><div className="bg-card border border-border rounded-xl p-5 mb-6 inline-block"><div className="text-subtle-foreground text-xs uppercase tracking-widest mb-1">Total revenue from completed gigs</div><div className="text-primary text-3xl font-bold">£{totalRevenue.toLocaleString()}</div><div className="text-subtle-foreground text-xs mt-1">{bookings.length} gig{bookings.length!==1?'s':''} completed</div></div>{bookings.length===0&&<div className="text-center py-16 text-subtle-foreground text-sm">No completed gigs yet</div>}<div className="flex flex-col gap-3">{bookings.map(b=>(<div key={b.id} className="bg-card border border-border border-l-4 border-l-info rounded-xl p-4"><div className="flex items-center justify-between gap-4"><div><div className="text-foreground font-semibold">{b.venues?.name}</div>{b.event_name&&<div className="text-muted-foreground/80 text-xs mt-0.5">{b.event_name}</div>}<div className="flex gap-3 text-xs text-muted-foreground/80 mt-2 flex-wrap"><span className="inline-flex items-center gap-1.5"><NavIcon name="calendar" className="w-3.5 h-3.5"/>{new Date(b.starts_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span>{b.artists?.stage_name&&<span className="inline-flex items-center gap-1.5"><NavIcon name="music" className="w-3.5 h-3.5"/>{b.artists.stage_name}</span>}</div></div><div className="flex flex-col items-end gap-1"><span className="text-primary font-bold">£{(b.fee_venue||0).toLocaleString()}</span><span className="text-xs bg-info/15 text-info px-2 py-0.5 rounded-full">Complete</span></div></div><div className="mt-3 pt-3 border-t border-border"><button onClick={()=>router.push('/agency/invoices')} className="text-xs text-primary hover:underline">View invoice →</button></div></div>))}</div></div></div></div>)}