'use client'
import{useState}from'react'
import{useRouter}from'next/navigation'
import AgencySidebar from'@/components/AgencySidebar'
export default function InviteArtistPage(){
const router=useRouter()
const[email,setEmail]=useState('')
const[stageName,setStageName]=useState('')
const[fullName,setFullName]=useState('')
const[loading,setLoading]=useState(false)
const[success,setSuccess]=useState(false)
const[error,setError]=useState('')
async function handleInvite(e){e.preventDefault();setLoading(true);setError('')
const res=await fetch('/api/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})})
const data=await res.json()
if(!res.ok){setError(data.error||'Failed to send invite');setLoading(false);return}
setSuccess(true);setLoading(false)}
if(success)return(<div className="min-h-screen bg-[#0E1117] flex"><AgencySidebar/><div className="flex-1 flex flex-col"><div className="bg-[#151A22] border-b border-[#263044] px-8 h-14 flex items-center gap-3"><button onClick={()=>router.push('/agency/roster')} className="text-[#6A7A8A] hover:text-white text-sm">Back</button><div className="text-white font-semibold">Invite Artist</div></div><div className="p-8 max-w-md"><div className="bg-[#151A22] border border-[#263044] rounded-xl p-8 text-center"><div className="text-green-400 text-4xl mb-4">✓</div><h2 className="text-white text-xl font-semibold mb-2">Invite sent</h2><p className="text-[#6A7A8A] text-sm mb-6">An invite email has been sent to <strong className="text-white">{email}</strong>. They will receive a link to create their account and access the artist portal.</p><div className="flex gap-3 justify-center"><button onClick={()=>{setSuccess(false);setEmail('');setStageName('');setFullName('')}} className="bg-[#1C2330] border border-[#263044] text-[#6A7A8A] text-sm px-5 py-2.5 rounded-lg hover:text-white transition-colors">Invite another</button><button onClick={()=>router.push('/agency/roster')} className="bg-[#C8A24A] text-[#0B0D10] font-bold text-sm px-5 py-2.5 rounded-lg hover:bg-[#D6B25E] transition-colors">View roster</button></div></div></div></div></div>)
return(<div className="min-h-screen bg-[#0E1117] flex"><AgencySidebar/><div className="flex-1 flex flex-col"><div className="bg-[#151A22] border-b border-[#263044] px-8 h-14 flex items-center gap-3"><button onClick={()=>router.push('/agency/roster')} className="text-[#6A7A8A] hover:text-white text-sm transition-colors">Back</button><div className="text-white font-semibold">Invite Artist</div></div><div className="p-8 max-w-md"><div className="bg-[#151A22] border border-[#263044] rounded-xl p-6"><h2 className="text-white text-lg font-semibold mb-1">Invite a new artist</h2><p className="text-[#6A7A8A] text-sm mb-6">They will receive an email with a link to create their account and access the Virtuoso artist portal.</p><form onSubmit={handleInvite} className="space-y-4"><div><label className="block text-[#8A96A8] text-xs uppercase tracking-widest mb-2">Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors" placeholder="artist@email.com"/></div><div><label className="block text-[#8A96A8] text-xs uppercase tracking-widest mb-2">Full name <span className="text-[#4E5A6A] normal-case tracking-normal">(for your records)</span></label><input type="text" value={fullName} onChange={e=>setFullName(e.target.value)} className="w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors" placeholder="e.g. Marcus Reid"/></div><div><label className="block text-[#8A96A8] text-xs uppercase tracking-widest mb-2">Stage name <span className="text-[#4E5A6A] normal-case tracking-normal">(for your records)</span></label><input type="text" value={stageName} onChange={e=>setStageName(e.target.value)} className="w-full bg-[#1C2330] border border-[#263044] rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#C8A24A] transition-colors" placeholder="e.g. DJ Reide"/></div>{error&&<div className="bg-red-900/20 border border-red-800 rounded-lg px-4 py-3 text-red-400 text-sm">{error}</div>}<button type="submit" disabled={loading} className="w-full bg-[#C8A24A] hover:bg-[#D6B25E] disabled:opacity-50 text-[#0B0D10] font-bold py-3 rounded-lg text-sm uppercase tracking-widest transition-colors">{loading?'Sending invite...':'Send invite'}</button></form></div></div></div></div>)}