'use client'
import{useEffect,useState}from'react'
import{supabase}from'@/lib/supabase'
import{useRouter}from'next/navigation'
import AgencySidebar from'@/components/AgencySidebar'
export default function UrgentPage(){
const router=useRouter()
const[bookings,setBookings]=useState([])
const[loading,setLoading]=useState(true)
useEffect(()=>{async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session){router.push('/login');return};const{data}=await supabase.from('bookings').select('*,venues(name),artists(stage_name)').eq('brag_status','G').order('date',{ascending:true});if(data)setBookings(data);setLoading(false)};load()},[]);
async function confirmBooking(id){const{error}=await supabase.from('bookings').update({brag_status:'R'}).eq('id',id);if(!error)setBookings(prev=>prev.filter(b=>b.id!==id))}
if(loading)return(<div className="min-h-screen bg-[#0E1117] flex items-center justify-center"><div className="text-[#C8A24A] text-4xl font-bold animate-pulse">VE</div></div>)
return(<div className="min-h-screen bg-[#0E1117] flex"><AgencySidebar/><div className="flex-1 flex flex-col"><div className="bg-[#151A22] border-b border-[#263044] px-8 h-14 flex items-center"><div className="text-white font-semibold">Needs Confirmation</div></div><div className="p-8">{bookings.length===0&&<div className="text-center py-16"><div className="text-green-400 text-4xl mb-4">✓</div><div className="text-white font-semibold mb-1">All clear</div><div className="text-[#4E5A6A] text-sm">No bookings need urgent confirmation</div></div>}<div className="flex flex-col gap-3">{bookings.map(b=>(<div key={b.id} className="bg-[#151A22] border border-[#263044] border-l-4 border-l-red-500 rounded-xl p-4"><div className="flex items-start justify-between gap-4"><div><div className="text-white font-semibold">{b.venues?.name}</div>{b.event_name&&<div className="text-[#6A7A8A] text-xs mt-0.5">{b.event_name}</div>}<div className="flex gap-3 text-xs text-[#6A7A8A] mt-2 flex-wrap"><span>📅 {new Date(b.date).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</span>{b.performance_time&&<span>🕐 {b.performance_time}</span>}{b.artists?.stage_name&&<span>🎧 {b.artists.stage_name}</span>}</div></div><div className="flex flex-col items-end gap-2"><span className="text-[#C8A24A] font-bold">£{(b.fee_venue||0).toLocaleString()}</span><span className="text-xs bg-red-900/30 text-red-400 px-2 py-0.5 rounded-full">Urgent</span></div></div><div className="mt-3 pt-3 border-t border-[#263044] flex gap-2"><button onClick={()=>confirmBooking(b.id)} className="bg-[#C8A24A] text-[#0B0D10] text-xs font-bold px-4 py-2 rounded-lg hover:bg-[#D6B25E] transition-colors">✓ Confirm now</button><button onClick={()=>router.push('/agency/bookings')} className="bg-[#1C2330] border border-[#263044] text-[#6A7A8A] text-xs px-4 py-2 rounded-lg hover:text-white transition-colors">View booking</button></div></div>))}</div></div></div></div>)}